### ISSUE TITLE
No proper error message for flight profile clean

### ISSUE THREAD

**Issue by KruseCtrl** [openflighthpc/flight-profile#58]
When running the command flight profile clean with no arguments, simply:
```
flight profile clean
```
i get the error message:
```
profile: undefined method `delete' for nil:NilClass
```

Not 100% certain, but it seems like it does actually clean 1 thing when running the command, which i'm not sure if thats a bug. E.g.
```
[flight@ip-172-31-19-83 ~]$ flight profile list
┌────────┬──────────┬────────┐
│ Node   │ Identity │ Status │
├────────┼──────────┼────────┤
│ login1 │ login    │ failed │
│ node01 │ compute  │ failed │
│ node02 │ compute  │ failed │
└────────┴──────────┴────────┘
[flight@ip-172-31-19-83 ~]$ flight profile clean
profile: undefined method `delete' for nil:NilClass
[flight@ip-172-31-19-83 ~]$ flight profile list
┌────────┬──────────┬───────────┐
│ Node   │ Identity │ Status    │
├────────┼──────────┼───────────┤
│ node01 │ compute  │ failed    │
│ node02 │ compute  │ failed    │
│ login1 │          │ available │
└────────┴──────────┴───────────┘
[flight@ip-172-31-19-83 ~]$ flight profile clean
profile: undefined method `delete' for nil:NilClass
[flight@ip-172-31-19-83 ~]$ flight profile list
┌────────┬──────────┬───────────┐
│ Node   │ Identity │ Status    │
├────────┼──────────┼───────────┤
│ node02 │ compute  │ failed    │
│ login1 │          │ available │
│ node01 │          │ available │
└────────┴──────────┴───────────┘
[flight@ip-172-31-19-83 ~]$ flight profile clean
profile: undefined method `delete' for nil:NilClass
[flight@ip-172-31-19-83 ~]$ flight profile list
┌────────┬──────────┬───────────┐
│ Node   │ Identity │ Status    │
├────────┼──────────┼───────────┤
│ login1 │          │ available │
│ node01 │          │ available │
│ node02 │          │ available │
└────────┴──────────┴───────────┘
```

But it should still say something like "specify the node to clean" rather than undefined method.

**Comment by VoxSecundus** [comment]
The desired effect for `clean` without arguments is that it attempts to clean _all_ `failed` nodes; the optional argument is to limit it to one specific node. This is still unexpected output, however. Please could you post an instance of the error with a `--trace` on the command so the developer who picks this up has a more specific idea of where the error occurs? Please also include a `cat` of your `etc/config.yml`.

**Comment by KruseCtrl** [comment]
```
[flight@ip-172-31-19-83 ~]$ flight profile clean --trace
Traceback (most recent call last):
	28: from /opt/flight/opt/runway/embedded/bin/bundle:23:in `<main>'
	27: from /opt/flight/opt/runway/embedded/bin/bundle:23:in `load'
	26: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	25: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	24: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	23: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	22: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	21: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	20: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	19: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	17: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	16: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	15: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	14: from /opt/flight/opt/runway/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	13: from bin/profile:19:in `<top (required)>'
	12: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/cli.rb:8:in `run!'
	11: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/error_handler.rb:43:in `start'
	10: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/cli.rb:9:in `block in run!'
	 9: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/cli.rb:18:in `run'
	 8: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/runner.rb:88:in `run'
	 7: from /opt/flight/opt/profile/vendor/ruby/2.7.0/gems/commander-openflighthpc-2.2.0/lib/commander/command.rb:34:in `run!'
	 6: from /opt/flight/opt/profile/lib/profile/commands.rb:19:in `method_missing'
	 5: from /opt/flight/opt/profile/lib/profile/command.rb:14:in `run!'
	 4: from /opt/flight/opt/profile/lib/profile/commands/clean.rb:28:in `run'
	 3: from /opt/flight/opt/profile/lib/profile/commands/clean.rb:28:in `each'
	 2: from /opt/flight/opt/profile/lib/profile/commands/clean.rb:29:in `block in run'
	 1: from /opt/flight/opt/profile/lib/profile/node.rb:92:in `delete'
/opt/flight/opt/profile/lib/profile/inventory.rb:39:in `remove_node': undefined method `delete' for nil:NilClass (NoMethodError)
profile: undefined method `delete' for nil:NilClass
```

**Comment by KruseCtrl** [comment]
```
[flight@ip-172-31-19-83 ~]$ cat etc/config.yml
cat: etc/config.yml: No such file or directory
```
